/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FestasRouteImport } from './routes/festas'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FestaCodeRouteImport } from './routes/festa.$code'

const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FestasRoute = FestasRouteImport.update({
  id: '/festas',
  path: '/festas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FestaCodeRoute = FestaCodeRouteImport.update({
  id: '/festa/$code',
  path: '/festa/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/festas': typeof FestasRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registrar': typeof RegistrarRoute
  '/festa/$code': typeof FestaCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/festas': typeof FestasRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registrar': typeof RegistrarRoute
  '/festa/$code': typeof FestaCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/festas': typeof FestasRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/registrar': typeof RegistrarRoute
  '/festa/$code': typeof FestaCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amigos'
    | '/auth'
    | '/eventos'
    | '/explorar'
    | '/festas'
    | '/perfil'
    | '/ranking'
    | '/registrar'
    | '/festa/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amigos'
    | '/auth'
    | '/eventos'
    | '/explorar'
    | '/festas'
    | '/perfil'
    | '/ranking'
    | '/registrar'
    | '/festa/$code'
  id:
    | '__root__'
    | '/'
    | '/amigos'
    | '/auth'
    | '/eventos'
    | '/explorar'
    | '/festas'
    | '/perfil'
    | '/ranking'
    | '/registrar'
    | '/festa/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmigosRoute: typeof AmigosRoute
  AuthRoute: typeof AuthRoute
  EventosRoute: typeof EventosRoute
  ExplorarRoute: typeof ExplorarRoute
  FestasRoute: typeof FestasRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  RegistrarRoute: typeof RegistrarRoute
  FestaCodeRoute: typeof FestaCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festas': {
      id: '/festas'
      path: '/festas'
      fullPath: '/festas'
      preLoaderRoute: typeof FestasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festa/$code': {
      id: '/festa/$code'
      path: '/festa/$code'
      fullPath: '/festa/$code'
      preLoaderRoute: typeof FestaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmigosRoute: AmigosRoute,
  AuthRoute: AuthRoute,
  EventosRoute: EventosRoute,
  ExplorarRoute: ExplorarRoute,
  FestasRoute: FestasRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  RegistrarRoute: RegistrarRoute,
  FestaCodeRoute: FestaCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
